export type OrderRecord = {
  id: number;
  status: string;
  client_id: string;
  consignee: string | null;
  purchase_order: number | null;
  plant: string | null;
  created_at: string;
  dispatched_at: string | null;
  line_number: number;
  product_id: string;
  net_weight_ton: number;
  gross_weight_ton: number | null;
  width_mm: number | null;
  length_mm: number | null;
  thickness_mm: number | null;
  ofa_id: number | null;
  pallet_id: string | null;
  pallet_date: string | null;
  updated_at: string | null;
};
