export type ProductRecord = {
  id: string;
  gauge: string;
  thickness: number;
  client_id: string;
  orientation: string | null;
  internal_diameter: number | null;
  external_diameter: number | null;
  min_weight: number | null;
  max_weight: number | null;
  width: number | null;
  min_lot: number | null;
  part_number: string | null;
  packaging_code: string | null;
  oiling: string | null;
  flatness: string | null;
  process: string | null;
  finish: string | null;
  form: string | null;
  consignee: string | null;
  grade_pn: string | null;
  width_pn: number | null;
  pieces_per_package: number | null;
  shipping_packaging: string | null;
  max_pallet_width: number | null;
  max_pallet_height: number | null;
  created_at: string | null;
  updated_at: string | null;
};
